# Server
server.port=8084

# Spring
spring.application.name=processor-service

# Kafka
spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=io.confluent.kafka.serializers.KafkaAvroSerializer
spring.kafka.producer.properties.schema.registry.url=http://schema-registry:8081

spring.kafka.consumer.group-id=video-processor-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=io.confluent.kafka.serializers.KafkaAvroDeserializer
spring.kafka.consumer.properties.schema.registry.url=http://localhost:8081
spring.kafka.consumer.properties.specific.avro.reader=true

# MinIO
minio.endpoint=http://localhost:9000
minio.public-endpoint=http://localhost:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin
minio.bucket-name=video-bucket

# Video Processing Qualities
video.processing.fast[0].name=360p
video.processing.fast[0].width=640
video.processing.fast[0].height=360
video.processing.fast[0].bandwidth=800000

video.processing.slow[0].name=240p
video.processing.slow[0].width=426
video.processing.slow[0].height=240
video.processing.slow[0].bandwidth=400000

video.processing.slow[1].name=480p
video.processing.slow[1].width=854
video.processing.slow[1].height=480
video.processing.slow[1].bandwidth=1400000

video.processing.slow[2].name=720p
video.processing.slow[2].width=1280
video.processing.slow[2].height=720
video.processing.slow[2].bandwidth=2800000

video.processing.slow[3].name=1080p
video.processing.slow[3].width=1920
video.processing.slow[3].height=1080
video.processing.slow[3].bandwidth=5000000

# HLS settings
video.processing.hls-time=10
video.processing.hls-list-size=0
