# Server
server.port=8081

# Spring
spring.application.name=auth-service

# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/videodb
spring.datasource.username=video_user
spring.datasource.password=video_pass

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT
jwt.secret=mySecretKeyForJwtGenerationShouldBeAtLeast32Chars
jwt.expiration=86400000