# Server
server.port=8080

# Spring
spring.application.name=api-gateway

# Cloud Gateway Routes
# Spring Cloud Gateway Routes
spring.cloud.gateway.routes[0].id=auth
spring.cloud.gateway.routes[0].uri=http://auth-service:8080
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.routes[1].id=upload-upload
spring.cloud.gateway.routes[1].uri=http://upload-service:8080
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/videos/upload
spring.cloud.gateway.routes[1].predicates[1]=Method=POST

spring.cloud.gateway.routes[2].id=upload-delete
spring.cloud.gateway.routes[2].uri=http://upload-service:8080
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/videos/**
spring.cloud.gateway.routes[2].predicates[1]=Method=DELETE

spring.cloud.gateway.routes[3].id=stream
spring.cloud.gateway.routes[3].uri=http://stream-service:8080
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/videos/**,/api/stream/**,/internal/**

spring.cloud.gateway.routes[4].id=frontend
spring.cloud.gateway.routes[4].uri=http://frontend:80
spring.cloud.gateway.routes[4].predicates[0]=Path=/**

# JWT
jwt.secret=mySecretKeyForJwtGenerationShouldBeAtLeast32Chars

# Logging
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.com.example.gateway=DEBUG

# Management Endpoints
management.endpoints.web.exposure.include=health,info,prometheus,metrics

# Metrics Distribution
management.metrics.distribution.percentiles-histogram.http.server.requests=true