events {
    worker_connections 10000;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    sendfile on;
    tcp_nopush on;
    keepalive_timeout 65;
    client_max_body_size 0;

    proxy_cache_path /var/cache/nginx
        levels=1:2
        keys_zone=minio_cache:100m
        max_size=10g
        inactive=24h
        use_temp_path=off;

    # Только после этого подключаем conf.d
    include /etc/nginx/conf.d/*.conf;
}