# Server
server.port=8083

# Spring
spring.application.name=stream-service

# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/videodb
spring.datasource.username=video_user
spring.datasource.password=video_pass

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update

# MinIO
minio.endpoint=http://localhost:9000
minio.public-endpoint=http://localhost:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin
minio.bucket-name=video-bucket

# ===== Redis =====
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:redis}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
spring.data.redis.timeout=2000ms

# ===== Cache =====
cache.video-list-ttl-seconds=30
cache.video-ttl-seconds=60

# ===== Kafka =====
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=io.confluent.kafka.serializers.KafkaAvroDeserializer
spring.kafka.consumer.properties.schema.registry.url=${SCHEMA_REGISTRY_URL:http://schema-registry:8081}
spring.kafka.consumer.properties.specific.avro.reader=true

# Management Endpoints
management.endpoints.web.exposure.include=health,info,prometheus,metrics

# Metrics Distribution
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.enable.hikaricp=true

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

logging.level.org.springframework.cloud.gateway=DEBUG