# Server
server.port=8083

# Spring
spring.application.name=stream-service

# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/videodb
spring.datasource.username=video_user
spring.datasource.password=video_pass

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update

# MinIO
minio.endpoint=http://localhost:9000
minio.public-endpoint=http://localhost:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin
minio.bucket-name=video-bucket